
# 清理后台日志
echo "清理后台日志"
echo "=============================================================="
cat /dev/null > nohup.out
echo "清理完毕"
echo "=============================================================="

# 心跳服务
echo "开始部署心跳包服务"
echo "=============================================================="
screen -dmUS "X"
echo "创建screen"
screen -S "X" -X stuff "cd bilibili-pcheartbeat"
screen -S "X" -X stuff "\n"
echo "进入目录"
screen -S "X" -X stuff "node app.js"
screen -S "X" -X stuff "\n"
echo "服务启动"
echo "=============================================================="

# B站脚本
echo "开始部署BiliHelper服务"
echo "=============================================================="
screen -dmUS "B1"
echo "创建用户1的screen"
screen -S "B1" -X stuff "cd BiliHelper-personal"
screen -S "B1" -X stuff "\n"
echo "进入目录"
screen -S "B1" -X stuff "php7.4 index.php user1.conf"
screen -S "B1" -X stuff "\n"
echo "用户1部署完毕"

screen -dmUS "B2"
echo "创建用户2的screen"
screen -S "B2" -X stuff "cd BiliHelper-personal"
screen -S "B2" -X stuff "\n"
echo "进入目录"
screen -S "B2" -X stuff "php7.4 index.php user2.conf"
screen -S "B2" -X stuff "\n"
echo "用户2部署完毕"
echo "=============================================================="

# 录制脚本
echo "开始部署录播脚本"
echo "=============================================================="
screen -dmUS "L"
echo "创建screen"
screen -S "L" -X stuff "nohup record/record_new.sh twitcastpy 8ra195 -o record_video/8ra195 -u baidupcs3:45468736:record_video/8ra195 -dt all &"
screen -S "L" -X stuff "\n"
screen -S "L" -X stuff "\n"
echo "みけねこ"
screen -S "L" -X stuff "nohup record/record_new.sh twitcastpy miso_ssw -o record_video/miso_ssw -u baidupcs3:45468736:record_video/miso_ssw -dt all &"
screen -S "L" -X stuff "\n"
screen -S "L" -X stuff "\n"
echo "miso"
screen -S "L" -X stuff "nohup record/record_new.sh twitcastpy masimasi0 -o record_video/masimasi0 -u baidupcs3:45468736:record_video/masimasi0 -dt all &"
screen -S "L" -X stuff "\n"
screen -S "L" -X stuff "\n"
echo "佐藤希TC"
screen -S "L" -X stuff "nohup record/record_new.sh youtube UCmrOHKPhWV1epCbTObd3eaQ -o record_video/satonozomi -u baidupcs3:45468736:record_video/satonozomi -dt all &"
screen -S "L" -X stuff "\n"
screen -S "L" -X stuff "\n"
echo "佐藤希Youtube"
screen -S "L" -X stuff "clear"
screen -S "L" -X stuff "\n"
echo "清屏"
screen -S "L" -X stuff "jobs"
screen -S "L" -X stuff "\n"
echo "显示现存脚本"
echo "=============================================================="

# ASF
echo "开始部署ASF服务"
echo "=============================================================="
screen -dmUS "ASF"
echo "创建screen"
screen -S "ASF" -X stuff "cd ASF"
screen -S "ASF" -X stuff "\n"
echo "进入目录"
screen -S "ASF" -X stuff "./ArchiSteamFarm"
screen -S "ASF" -X stuff "\n"
echo "启动ASF"
echo "请手动输入 screen -U -r ASF 进入ASF填写Steam验证码"
